# NG 5 
Matrix

In [2]:
import numpy as np
import matplotlib.pyplot as plt

1. Buatlah Tensor di bawah ini dengan Python:

       Jawab:

In [40]:
Tensor=np.array([
    [[23,50],[7,12]],
    [[57,67],[99,43]],
    [[75,21],[57,12]],
    [[87,26],[18,84]]
])
print(Tensor)

[[[23 50]
  [ 7 12]]

 [[57 67]
  [99 43]]

 [[75 21]
  [57 12]]

 [[87 26]
  [18 84]]]


2. Lakukan perkalian terhadap matrix berikut: 

        Jawab:

In [30]:
matrix_A=np.array([[23,50,19],
                  [7,12,109],
                  [57,67,98]])
matrix_B=np.array([[17,
                   22,
                   19]])

print("Membuat Matrix A")
print(matrix_A)
print("")
print("Membuat Matrix B")
print(matrix_B)
print("")
print("Perkalian Matrix A dan B")
print(matrix_B*matrix_A)


Membuat Matrix A
[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]

Membuat Matrix B
[[17 22 19]]

Perkalian Matrix A dan B
[[ 391 1100  361]
 [ 119  264 2071]
 [ 969 1474 1862]]


3. Lakukan Transpose, hitung determinan, dan inverse 
    terhadap matrix dibawah ini:

        Jawab:

In [4]:
matrix_A=np.array([[23,50,19],
                  [7,12,109],
                  [57,67,98]])

print('Matrix A :')
print(matrix_A)

print('Transpose:')
print(matrix_A.T)
print('')

print('Inverse :')#Inverse
np.linalg.inv(matrix_A.T)

Matrix A :
[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]
Transpose:
[[ 23   7  57]
 [ 50  12  67]
 [ 19 109  98]]

Inverse :


array([[-0.0466485 ,  0.04208034, -0.00163692],
       [-0.02761451,  0.00891552,  0.0099662 ],
       [ 0.03975819, -0.01807467, -0.00056341]])

In [37]:
print('Determinan :')#determinan
np.linalg.det(matrix_A.T)

Determinan :


131343.99999999997