# NG 6
Eigendecomposition

In [3]:
import numpy as np

1. mencari nilai eigenvector 

In [29]:
A=np.array([[1,2],[3,4]])
B=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)
print(B)

[[1 2]
 [3 4]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print(A*B) # nilai Vektor

[[ 1 -3]
 [ 6 12]]


In [15]:
print(C/A) # nilai Matrix

[[ 1. -1.]
 [ 6.  4.]]


In [16]:
nilai_vektor = np.array([1,3])
nilai_matrix = np.array([[1,-1],[6,4]])

print('nilai Vektor')
print(nilai_vektor)

print('nilai Matrix')
print(nilai_matrix)

nilai Vektor
[1 3]
nilai Matrix
[[ 1 -1]
 [ 6  4]]


In [19]:
print('Perkalian,matrix * vektor Hasil :')
dot=nilai_matrix@nilai_vektor 
dot

Perkalian,matrix * vektor Hasil :


array([-2, 18])

In [25]:
#Mencari nilai eigen value
eigVal_nilai_matrix,eigVec_nilai_matrix=np.linalg.eig(nilai_matrix) 
print('Eigen Value :')
print(eigVal_nilai_matrix)
print('Eigen Vektor :')
print(eigVec_nilai_matrix)

Eigen Value :
[2.5+1.93649167j 2.5-1.93649167j]
Eigen Vektor :
[[-0.23145502+0.29880715j -0.23145502-0.29880715j]
 [ 0.9258201 +0.j          0.9258201 -0.j        ]]
